### ISSUE TITLE
is it possible to update a ZIP file ?

### ISSUE THREAD

**Issue by ultimaRatio** [mvdnes/zip-rs#17]
Hi,

Is it possible to update a file in a ZIP file without having to decompress and recompress all the files ?

**Comment by mvdnes** [comment]
I guess so. If the new file is smaller then you could use the space of the existing file and just update the size and crc. Otherwise you could leave a gap where the existing file is and just append the updated file to the end, and create a new directory.

Currently there is no support in this codebase however. Pull requests are always welcome.

**Comment by ultimaRatio** [comment]
ok, thanks for you answer.
