### ISSUE TITLE
Sanitization of windows file names

### ISSUE THREAD

**Issue by tirkarthi** [mvdnes/zip-rs#74]
Hi,

Recently snyk found a vulnerability in malicious filenames in archives being used to extract to unwanted paths which I assume from the [HN comments](https://news.ycombinator.com/item?id=17237295) is an old issue. I tried the vulnerable file available at the [repo](https://github.com/snyk/zip-slip-vulnerability) . I found that the filenames are sanitized and there is a [test case](https://github.com/mvdnes/zip-rs/blob/362f12dc9b8ccda911caafd45abc6d940fb871f8/src/types.rs#L106) for the same. It works fine on linux systems. On linux machines for `../../../../../../../tmp/evil.txt` it writes to `tmp/evil.txt` in the current folder

But I later found python to do some more additional validation on windows filenames. I couldn't try this on WIndows since I don't have access to a windows machine.

Python doc reference : https://docs.python.org/3/library/zipfile.html?highlight=zipfile#zipfile.ZipFile.extract
Python implementation : https://github.com/python/cpython/blob/b8c0845fee9277b1106ceecbf7592f8806c73ec8/Lib/zipfile.py#L1597

> If a member filename is an absolute path, a drive/UNC sharepoint and leading (back)slashes will be stripped, e.g.: ///foo/bar becomes foo/bar on Unix, and C:\foo\bar becomes foo\bar on Windows. And all ".." components in a member filename will be removed, e.g.: ../../foo../../ba..r becomes foo../ba..r. On Windows illegal characters (:, <, >, |, ", ?, and *) replaced by underscore (_).

Feel free to close this if it's irrelevant or I am missing something.

Thanks for the library.

**Comment by mvdnes** [comment]
The standard library of Rust parses a path into several [Component]s. The `file_name_sanitized` function of zip-rs removes all parts that are not 'normal'. So a '..', but also prefixes like 'C:\' or UNC paths are removed.

The vulnerability you mentioned should not be applicable because of these countermeasures. I do not replace the illegal characters for Windows, but do not think this should lead to a dangerous situation.

[Component]: https://doc.rust-lang.org/std/path/enum.Component.html

**Comment by tirkarthi** [comment]
Thanks for the reply and links. I am closing it for now then.
